/**
 * =============================================================================
 *
 * ORCID (R) Open Source
 * http://orcid.org
 *
 * Copyright (c) 2012-2014 ORCID, Inc.
 * Licensed under an MIT-Style License (MIT)
 * http://orcid.org/open-source-license
 *
 * This copyright and license information (including a link to the full license)
 * shall be included in its entirety in all copies or substantial portion of
 * the software.
 *
 * =============================================================================
 */
package org.orcid.api.common.security.filter.impl;

import org.custommonkey.xmlunit.Diff;
import org.custommonkey.xmlunit.XMLTestCase;
import org.junit.Test;
import org.orcid.core.security.DefaultPermissionChecker;
import org.orcid.core.security.visibility.filter.impl.VisibilityFilterImpl;
import org.orcid.jaxb.model.message.ExternalIdentifier;
import org.orcid.jaxb.model.message.Keyword;
import org.orcid.jaxb.model.message.OrcidMessage;
import org.orcid.jaxb.model.message.OtherName;
import org.orcid.jaxb.model.message.ResearcherUrl;
import org.orcid.jaxb.model.message.Visibility;
import org.springframework.test.util.ReflectionTestUtils;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;

import java.io.InputStream;

/**
 * @author Declan Newman (declan) Date: 16/03/2012
 */
public class VisibilityFilterImplTest extends XMLTestCase {

    private Unmarshaller unmarshaller;

    private VisibilityFilterImpl visibilityFilter = new VisibilityFilterImpl();

    private OrcidMessage protectedOrcidMessage;
    private OrcidMessage publicOrcidMessage;

    public VisibilityFilterImplTest() throws JAXBException {
        super("Test Visibility Filter");
        JAXBContext context = JAXBContext.newInstance(OrcidMessage.class);
        unmarshaller = context.createUnmarshaller();
    }

    @Test
    public void testFilterStripWithVisibilities() throws Exception {
        protectedOrcidMessage = getOrcidMessage("/orcid-protected-full-message-latest.xml");
        publicOrcidMessage = getOrcidMessage("/orcid-stripped-with-visibility-message-latest.xml");
        OrcidMessage orcidMessage = visibilityFilter.filter(cascadeSectionPrivacyToItems(protectedOrcidMessage), Visibility.PUBLIC);
        Diff myDiff = new Diff(publicOrcidMessage.toString(), orcidMessage.toString());
        assertEquals(publicOrcidMessage.toString(), orcidMessage.toString());
        assertTrue(myDiff.toString(), myDiff.similar());
    }

    private OrcidMessage getOrcidMessage(String s) throws JAXBException {
        InputStream inputStream = VisibilityFilterImplTest.class.getResourceAsStream(s);
        return (OrcidMessage) unmarshaller.unmarshal(inputStream);

    }
    
    /** Cascades section level privacy to items within that section that have null visibilities.
     * Affects ResearcherUrl, Keyword, OtherName, ExternalIdentifier.
     * 
     * Should be used before calling filter if the message was de-serialised from XML.
     * Subsequent filtering will be safe but Will result in information loss.
     * To avoid information loss, you should filter messages generated by manager classes instead.
     * 
     * @param messageToModify
     * @return
     */
    private OrcidMessage cascadeSectionPrivacyToItems(OrcidMessage m){
        for (Keyword k : m.getOrcidProfile().getOrcidBio().getKeywords().getKeyword())
            k.setVisibility(m.getOrcidProfile().getOrcidBio().getKeywords().getVisibility());
        
        for (ResearcherUrl r : m.getOrcidProfile().getOrcidBio().getResearcherUrls().getResearcherUrl())
            r.setVisibility(m.getOrcidProfile().getOrcidBio().getResearcherUrls().getVisibility());
        
        for (ExternalIdentifier id : m.getOrcidProfile().getOrcidBio().getExternalIdentifiers().getExternalIdentifier())
            id.setVisibility(m.getOrcidProfile().getOrcidBio().getExternalIdentifiers().getVisibility());
        
        for (OtherName on : m.getOrcidProfile().getOrcidBio().getPersonalDetails().getOtherNames().getOtherName())
            on.setVisibility(m.getOrcidProfile().getOrcidBio().getPersonalDetails().getOtherNames().getVisibility());
        
        return m;
    }
    
}
