/**
 * =============================================================================
 *
 * ORCID (R) Open Source
 * http://orcid.org
 *
 * Copyright (c) 2012-2014 ORCID, Inc.
 * Licensed under an MIT-Style License (MIT)
 * http://orcid.org/open-source-license
 *
 * This copyright and license information (including a link to the full license)
 * shall be included in its entirety in all copies or substantial portion of
 * the software.
 *
 * =============================================================================
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.18 at 12:45:00 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.orcid.org/ns/group-id", xmlns={
		@javax.xml.bind.annotation.XmlNs(prefix = "group-id", namespaceURI = "http://www.orcid.org/ns/group-id"),
		@javax.xml.bind.annotation.XmlNs(prefix = "common", namespaceURI = "http://www.orcid.org/ns/common"),},
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.orcid.jaxb.model.groupid_rc4;

