//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.09 at 01:52:56 PM BST 
//

package org.orcid.jaxb.model.message;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement(name = "agency-orcid")
public class AgencyOrcid extends OrcidIdBase implements Serializable {

    private static final long serialVersionUID = 1L;

    public AgencyOrcid() {
        super();
    }

    public AgencyOrcid(OrcidIdBase other) {
        super(other);
    }

    public AgencyOrcid(String path) {
        super(path);
    }
   
}
