/**
 * =============================================================================
 *
 * ORCID (R) Open Source
 * http://orcid.org
 *
 * Copyright (c) 2012-2013 ORCID, Inc.
 * Licensed under an MIT-Style License (MIT)
 * http://orcid.org/open-source-license
 *
 * This copyright and license information (including a link to the full license)
 * shall be included in its entirety in all copies or substantial portion of
 * the software.
 *
 * =============================================================================
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.09 at 01:52:56 PM BST 
//

package org.orcid.jaxb.model.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}orcid-works" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}orcid-grants" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}orcid-patents" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.orcid.org/ns/orcid}scope"/>
 *       &lt;attGroup ref="{http://www.orcid.org/ns/orcid}visibility"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "orcidWorks", "orcidGrants", "orcidPatents" })
@XmlRootElement(name = "orcid-activities")
public class OrcidActivities implements Serializable {

    @XmlElement(name = "orcid-works")
    protected OrcidWorks orcidWorks;
    @XmlElement(name = "orcid-grants")
    protected OrcidGrants orcidGrants;
    @XmlElement(name = "orcid-patents")
    protected OrcidPatents orcidPatents;

    /**
     * Gets the value of the orcidWorks property.
     * 
     * @return
     *     possible object is
     *     {@link OrcidWorks }
     *     
     */
    public OrcidWorks getOrcidWorks() {
        return orcidWorks;
    }

    /**
     * Sets the value of the orcidWorks property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidWorks }
     *     
     */
    public void setOrcidWorks(OrcidWorks value) {
        this.orcidWorks = value;
    }

    /**
     * Gets the value of the orcidGrants property.
     * 
     * @return
     *     possible object is
     *     {@link OrcidGrants }
     *     
     */
    public OrcidGrants getOrcidGrants() {
        return orcidGrants;
    }

    /**
     * Sets the value of the orcidGrants property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidGrants }
     *     
     */
    public void setOrcidGrants(OrcidGrants value) {
        this.orcidGrants = value;
    }

    /**
     * Gets the value of the orcidPatents property.
     * 
     * @return
     *     possible object is
     *     {@link OrcidPatents }
     *     
     */
    public OrcidPatents getOrcidPatents() {
        return orcidPatents;
    }

    /**
     * Sets the value of the orcidPatents property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidPatents }
     *     
     */
    public void setOrcidPatents(OrcidPatents value) {
        this.orcidPatents = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof OrcidActivities)) {
            return false;
        }

        OrcidActivities that = (OrcidActivities) o;

        if (orcidGrants != null ? !orcidGrants.equals(that.orcidGrants) : that.orcidGrants != null) {
            return false;
        }
        if (orcidPatents != null ? !orcidPatents.equals(that.orcidPatents) : that.orcidPatents != null) {
            return false;
        }
        if (orcidWorks != null ? !orcidWorks.equals(that.orcidWorks) : that.orcidWorks != null) {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int result = orcidWorks != null ? orcidWorks.hashCode() : 0;
        result = 31 * result + (orcidGrants != null ? orcidGrants.hashCode() : 0);
        result = 31 * result + (orcidPatents != null ? orcidPatents.hashCode() : 0);
        return result;
    }
}
