/**
 * =============================================================================
 *
 * ORCID (R) Open Source
 * http://orcid.org
 *
 * Copyright (c) 2012-2013 ORCID, Inc.
 * Licensed under an MIT-Style License (MIT)
 * http://orcid.org/open-source-license
 *
 * This copyright and license information (including a link to the full license)
 * shall be included in its entirety in all copies or substantial portion of
 * the software.
 *
 * =============================================================================
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.10 at 03:28:22 PM BST 
//

package org.orcid.jaxb.model.message;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p/>
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p/>
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlType(name = "work-external-identifier-type")
@XmlEnum
public enum WorkExternalIdentifierType implements Serializable {

    @XmlEnumValue("other-id")
    OTHER_ID("other-id", "Other identifier type"),
    @XmlEnumValue("asin")
    ASIN("asin", "Amazon Standard Identification Number"),
    @XmlEnumValue("asin-tld")
    ASIN_TLD("asin-tld", "ASIN top-level domain"),
    @XmlEnumValue("arxiv")
    ARXIV("arxiv", "ArXiv"),
    @XmlEnumValue("bibcode")
    BIBCODE("bibcode", "Bibcode"),
    @XmlEnumValue("doi")
    DOI("doi", "Digital object identifier"),
    @XmlEnumValue("eid")
    EID("eid", "Scopus Identifier"),
    @XmlEnumValue("isbn")
    ISBN("isbn", "International Standard Book Number"),
    @XmlEnumValue("issn")
    ISSN("issn", "International Standard Serial Number"),
    @XmlEnumValue("jfm")
    JFM("jfm", "Jahrbuch über die Fortschritte der Mathematik"),
    @XmlEnumValue("jstor")
    JSTOR("jstor", "JSTOR abstract"),
    @XmlEnumValue("lccn")
    LCCN("lccn", "Library of Congress Control Number"),
    @XmlEnumValue("mr")
    MR("mr", "Mathematical Reviews"),
    @XmlEnumValue("oclc")
    OCLC("oclc", "Online Computer Library Center"),
    @XmlEnumValue("ol")
    OL("ol", "Open Library"),
    @XmlEnumValue("osti")
    OSTI("osti", "Office of Scientific and Technical Information"),
    @XmlEnumValue("pmc")
    PMC("pmc", "PubMed Central article number"),
    @XmlEnumValue("pmid")
    PMID("pmid", "PubMed Unique Identifier"),
    @XmlEnumValue("rfc")
    RFC("rfc", "Request for Comments"),
    @XmlEnumValue("ssrn")
    SSRN("ssrn", "Social Science Research Network"),
    @XmlEnumValue("zbl")
    XBL("zbl", "Zentralblatt MATH");

    private final String value;
    private final String description;

    WorkExternalIdentifierType(String value, String description) {
        this.value = value;
        this.description = description;
    }

    public String value() {
        return value;
    }

    public String description() {
        return description;
    }

    public static WorkExternalIdentifierType fromValue(String value) {
        for (WorkExternalIdentifierType wit : WorkExternalIdentifierType.values()) {
            if (wit.value.equals(value)) {
                return wit;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
