################
#   DATABASE   # 
################

# Main database 
org.orcid.persistence.db.class=org.postgresql.Driver
org.orcid.persistence.db.dataSource=pooledDataSource
org.orcid.persistence.db.dialect=org.hibernate.dialect.PostgreSQLDialect
org.orcid.persistence.db.generateDdl=false
org.orcid.persistence.db.hibernateStatistics=true
org.orcid.persistence.db.idleConnectionTestPeriod=3600
org.orcid.persistence.db.initialPoolSize=5
org.orcid.persistence.db.maxPoolSize=20
org.orcid.persistence.db.maxStatements=50
org.orcid.persistence.db.minPoolSize=5
org.orcid.persistence.db.numHelperThreads=10
org.orcid.persistence.db.password=orcid
org.orcid.persistence.db.preferredTestQuery=select 1
org.orcid.persistence.db.showSql=false
org.orcid.persistence.db.testConnectionOnCheckin=true
org.orcid.persistence.db.url=jdbc:postgresql://localhost:5432/orcid?stringtype=unspecified
org.orcid.persistence.db.username=orcid

# Read only database
org.orcid.persistence.db.readonly.class=org.postgresql.Driver
org.orcid.persistence.db.readonly.dataSource=pooledDataSourceReadOnly
org.orcid.persistence.db.readonly.dialect=org.hibernate.dialect.PostgreSQLDialect
org.orcid.persistence.db.readonly.generateDdl=false
org.orcid.persistence.db.readonly.idleConnectionTestPeriod=3600
org.orcid.persistence.db.readonly.initialPoolSize=5
org.orcid.persistence.db.readonly.maxPoolSize=20
org.orcid.persistence.db.readonly.maxStatements=50
org.orcid.persistence.db.readonly.minPoolSize=5
org.orcid.persistence.db.readonly.password=orcidro
org.orcid.persistence.db.readonly.preferredTestQuery=select 1
org.orcid.persistence.db.readonly.showSql=false
org.orcid.persistence.db.readonly.testConnectionOnCheckin=true
org.orcid.persistence.db.readonly.url=jdbc:postgresql://localhost:5432/orcid?stringtype=unspecified
org.orcid.persistence.db.readonly.username=orcidro

# Features database
org.orcid.persistence.togglz.cache.ttl=0
org.orcid.persistence.togglz.db.class=org.postgresql.Driver
org.orcid.persistence.togglz.db.idleConnectionTestPeriod=3600
org.orcid.persistence.togglz.db.initialPoolSize=1
org.orcid.persistence.togglz.db.maxPoolSize=1
org.orcid.persistence.togglz.db.maxStatements=0
org.orcid.persistence.togglz.db.minPoolSize=1
org.orcid.persistence.togglz.db.numHelperThreads=5
org.orcid.persistence.togglz.db.password=orcid
org.orcid.persistence.togglz.db.preferredTestQuery=select 1
org.orcid.persistence.togglz.db.testConnectionOnCheckin=true
org.orcid.persistence.togglz.db.url=jdbc:postgresql://localhost:5432/features
org.orcid.persistence.togglz.db.username=orcid

################
#     CORE     # 
################
# Jersey development mode
org.orcid.utils.jersey.development_mode=true

org.orcid.utils.jwtKey=k@8f0!o35#*osx#%so#@9tgiSh2h@8fhso!ldo@*35!hfHDoa1if7alk
org.orcid.utils.jwtExpirationInMinutes=240

# ORCID URI's, no trailing slashes, please
org.orcid.core.aboutUri=https://info.orcid.org
org.orcid.core.apiBaseUri=https://api.dev.orcid.org
org.orcid.core.baseUri=https://dev.orcid.org
org.orcid.core.internalApiBaseUri=http://localhost:8080/orcid-internal-api
org.orcid.core.pubBaseUri=https://pub.dev.orcid.org

# Mailgun
com.mailgun.alt.apiUrl=https://api.mailgun.net/v2/samples.mailgun.org/messages
com.mailgun.alt.notify.apiUrl=https://api.mailgun.net/v2/samples.mailgun.org/messages
com.mailgun.alt.verify.apiUrl=https://api.mailgun.net/v2/samples.mailgun.org/messages
com.mailgun.apiKey=XXXX
com.mailgun.apiUrl=https://api.mailgun.net/v2/samples.mailgun.org/messages
com.mailgun.marketing.apiUrl=https://api.mailgun.net/v2/samples.mailgun.org/messages
com.mailgun.notify.apiUrl=https://api.mailgun.net/v2/samples.mailgun.org/messages
com.mailgun.regexFilter=(?i).*(orcid\.org|mailinator\.com)$
com.mailgun.testmode=true
com.mailgun.verify.apiUrl=https://api.mailgun.net/v2/samples.mailgun.org/messages

# Unclaimed records wait period
org.orcid.core.claimWaitPeriodDays:1

# Oauth
org.orcid.core.oauth.auth_code.expiration_minutes=1440
org.orcid.core.oauth.supportRefreshToken=true
org.orcid.core.token.implicit_validity_seconds=600
org.orcid.core.token.read_validity_seconds=631138519
org.orcid.core.token.write_validity_seconds=3600

# OpenID connect JWKS location.  Use filesystem location for prod, or an escaped JSON string in jwks_test_key for dev.
# Generate a key here: https://mkjwk.org/
org.orcid.openid.jwksKeyName=qa-orcid-org-r9afl7qf6hcg7g9ngszu5nt7gzf0ea6i
org.orcid.openid.jwksTestKey={"keys": [ { "p": "5j8V_z7xfY9RinPicNKzX8zhd7we99krUJ4x2SQk8tgQjSrjBUBSZyIhqSodVkXM_INoATXHQFzFsu0Cl6bu6w", "kty": "RSA", "q": "ymli4OvEHW59LN9ts-WHUn9SEel_MfX9sAFbb5mG400VV9fGBQw6NMOvo-tmapYqSulAY2sCPinkG-M2203r8w", "d": "Yw8w_uexxenYTwuFScqRcZtmLPnd1EcXbGGvGr67KibQtB8k2AZV1tr-7Hkz72ONpIa2jjG7m2VSq8nnPMu2I1ipCQRYXXCsh6bt9pJ32Tpd8doU9JMw6a7Lg3_qYqAjX72btEvdKBvXwoWq1NvVbZYF75bPx-2l_kXRWoHWhqU", "e": "AQAB", "use": "sig", "kid": "qa.orcid.org", "qi": "I-Cj5nsLgqyiSnebbdksoF-66tlc6ZbD-b5ER6wkBchPZzvFEeG0CQTE6_b_Q3zqAWNRQKOIrK8WZMhUMNroWA", "dp": "U1rXbdatupUeIg-eFNZS1gXoQl66n2PhyIfc6A2ryrbqFxFFqusEag3zPbjfchJHCcvQ5U9A2U48zG_9lkV7DQ", "dq": "EqLVWcQbUGJl4AXKQe_2H6BdXAzVizIM43Gci4_lHXRxbJ8POlO_4C_MMhlwWovs5OzI4t5tXG_a8r5exJ5OBQ", "n": "tgyQKd8Gn4XG4NJWr2dRVDDXprJ38WQIfu10Jb6WQbpmv5lD5b-tgsQmReg9zHBXAazZfiOiObWK-wsrlkOwB2ymVKIRCWrLGXMlfrUoh-XbPRtqnRDnEHpVIAjQS_RIBXYGBsUBlO-vyxDdR8mE0cQsMoYl6-0p68WM1xZ1ghE" }, { "p": "_gU3QI9hq0eUSRHM8JNgLNRrIBTBN5kPgsaWsc5xgM6GEjzm5hP1-MQeR8ZTk4VW4irM9aOqedJwOmdXW1lQ4c6SdBa-cI0M9mtJJ6mcErPQGNfPwW7lKYNvrNaBP6KJ6YSpzRVUaJaIxJEHghNc1bCDQkYG3CM7SPzD9pducK0", "kty": "RSA", "q": "xKhQFoeVunUuEpoUtmZI_aATSqdC9aUcGSIh1vZnFjikgnUHD71kT_oLFGkBEh60KeVxoQSd3C7mtvIieT9DptXptFl7ij22I5sVpelaQ8E-TSPDdw3_cnpT3zZafH-bDdX05NB5HUyuiP1ZjMGMeJ3OLNw3Ya-1cQoqBnoZ_is", "d": "qC5vRQS0Uaku3rGhG3w2nSim9o6gncB5swbcnej-IGngLthQl2v4Fg9QiKxZ980T6oHa3vcgBzy1CBeHd39mxs1NtIsefDtfoCQ-KSmVxafRyjoGrnuag_yFKt00pvIGrzJbeXbqakXuXNvH7C__GdNVi29ZUQmYNc_Q8ydoUnE8A6sgFLLjo4G2mi1QAs49yQcHDFOcPhpkGeG2PcR3p2bMOZN8mgADgtSHClWsNwlfgH3WZBrNRjRqqFEFzDP548ZMwr9bU0NxsqYBOP_8bq-Hr-0rlMdpGRy9WRvK3A5FLE1cGYF8shkCk5-Pw6UluEv2oTGvt0kohUK920pT4Q", "e": "AQAB", "use": "sig", "kid": "qa-orcid-org-r9afl7qf6hcg7g9ngszu5nt7gzf0ea6i", "qi": "FOiZvnlZ20hYtKGmGHjWPAYmIwQ-oW4mnKcV_wnzLaXYH8cQHfEnGrgIakZsdL6xie3JbfxzPzEJHBq05yiB8YVq6K7DbmQy5uHTDF8DdIXy-8kXseMSD5L5QN0ls0MuHljryyoPfa3ZnV9H48o6SKg4RRkZn0Olh6EARyDLIvg", "dp": "PlVlU5BbtT4hYzTdB4QCq72MdBjjuRL0PXEh9YvlSmhjegI73uWzDFKD47UFOUQVJ_a8yOJaqP48z_gf9aibMm4QfjA-lzvlnGqDTxpN1EEPpaj_sEXYMjGwq8cPfGAUW5tUV6EOT4PxF9tG7mJ1-3IPI6ovcMGsgKKWK-LJFRk", "dq": "qeQiNCRz1H4xDD7yT9Uzj3A_2kl_TkmSaaAUDeoWiprqfA1vyUg7peAEvGAuXaIK0Pr33DvpyHL4O-oYoBhocHPyjyySzo2bkU0EOa3LnicOlIOl9G8yVIqbdIU3TMDMifphs17qksZRLeV4_GGk4fqqSBUC_zBVlk9KmQfY9rs", "n": "wyMBMaxlHcZQ2tsbRWdmPF3IMf0rCj9y-NdxmZiuznQQkr0VTOfnf64WMJuhrORoBcFC_Y_G2ZHeDEag8fHjRoW0MVnX0rjcbbwCKenE3BNSsh3qwU1TJ-8SnZ_gsR1XFEqFvK371fE1qAw0UfqmEfVyMG07FZGQSUcUC8kVtXelgyhAlz4jbqW5SgnomlSYuwmcqKqj2ciib8713fePjujTPeuq7vpxXV7wmiHJ3aVyB5EWsX9dIm7JTknxceH9jjSM_JmeoszXX7oZqDcHUWoWbhmb4Ul4OZ25Eq7UQy48WLpTS5Ycz1FuEHuT8xUKDoL1L16293Ai-AY0dj2TDw" } ] }
org.orcid.openid.jwksLocation=

# node number and total number of nodes.
org.orcid.core.node = 1
org.orcid.core.numberOfNodes = 1

# CORS allowed domains
org.orcid.security.cors.allowed_domains=dev.orcid.org
org.orcid.security.two_factor.token_ttl=5

# Messaging
# Replace with tcp://domain.com:61616 in live to point at ActiveMQ location
org.orcid.messaging.brokerURL=tcp://localhost:61616?jms.useAsyncSend=true&jms.useCompression=true
org.orcid.persistence.messaging.enabled=false

# Slack
org.orcid.core.slack.channel=system-alerts-dev
org.orcid.core.slack.webhookUrl=

# Crossref finder
org.orcid.core.finder.crossref.clientid=APP-9999999999999901
org.orcid.core.finder.crossref.enabled=true
org.orcid.core.finder.crossref.endpoint=https://api.crossref.org/works?filter=orcid:

# Datacite finder
org.orcid.core.finder.datacite.clientid=APP-9999999999999901
org.orcid.core.finder.datacite.enabled=true
org.orcid.core.finder.datacite.endpoint=https://api.datacite.org/works?query=

# Bulk read max
org.orcid.core.works.bulk.read.max=100

# Bulk write max
org.orcid.core.works.bulk.write.max=100

# Client details id for issn sources
org.orcid.core.issn.source=APP-POCQZAUC70YOFL9R

# Orgs grouping
org.orcid.core.orgs.query=(org-disambiguated-name-case-insensitive:"%s" )^200.0 (org-disambiguated-name:"%s" )^1.0 (org-names:"%s")^0.7  (org-names:"%s"~15)^0.5 (org-names:*%s*)^0.01
org.orcid.core.orgsToGroup.query=select a.* from org_disambiguated a full outer join org_disambiguated_external_identifier b on a.id = b.org_disambiguated_id where b.identifier_type = 'FUNDREF' and a.source_type='ROR'

################
#      API     #
################

# Google analytics
org.orcid.core.api.analytics.endpoint=https://www.google-analytics.com/collect
org.orcid.core.api.analytics.trackingCode=XXX

# Swagger
org.orcid.swagger.tokenendpoint=https://localhost:8443/orcid-api-web/oauth/token
org.orcid.swagger.authendpoint=https://localhost:8443/orcid-web/oauth/authorize

################
# INTERNAl API #
################

# Database
org.orcid.persistence.internal_api.db.initialPoolSize=1
org.orcid.persistence.internal_api.db.maxPoolSize=3
org.orcid.persistence.internal_api.db.minPoolSize=1
org.orcid.persistence.internal_api.db.readonly.initialPoolSize=1
org.orcid.persistence.internal_api.db.readonly.maxPoolSize=3
org.orcid.persistence.internal_api.db.readonly.minPoolSize=1

################
#   SCHEDULER  #
################

org.orcid.scheduler.web.processWebhooks:25 * * * * *
org.orcid.scheduler.web.sendEmailMessages:05 * * * * *
org.orcid.scheduler.web.orgImportsCronConfig=0 0 0 * * *
org.orcid.scheduler.api.profile.validation.cronConfig=0 */10 * * * *

# Indexing delay after record last modified
org.orcid.scheduler.web.processProfilesPendingIndexingDelaySeconds=5

# Validation of public records via v3 api
org.orcid.scheduler.api.profile.validation.baseUrl=https://localhost:8443/orcid-pub-web/v3.0/
org.orcid.scheduler.api.profile.validation.batchSize=100
org.orcid.scheduler.api.profile.validation.cronConfig=0 */10 * * * *
org.orcid.scheduler.api.profile.validation.developmentMode=true

# Automated org importer
org.orcid.core.orgs.clients.userAgent=ORCID Org ID loader
org.orcid.core.orgs.load.slackChannel=#tech-webhook-test
org.orcid.core.orgs.load.slackUser=Org Imports

# Ringgold org importer
org.orcid.core.orgs.ringgold.enabled=false
org.orcid.core.orgs.ringgold.ftpHost=host
org.orcid.core.orgs.ringgold.ftpLocalFilePath=/path
org.orcid.core.orgs.ringgold.ftpPassword=something
org.orcid.core.orgs.ringgold.ftpPort=20
org.orcid.core.orgs.ringgold.ftpRemoteFilePath=/path
org.orcid.core.orgs.ringgold.ftpUsername=something

# Fundref org importer
org.orcid.core.orgs.fundref.enabled=false
org.orcid.core.orgs.fundref.latestReleaseUrl=https://some/path
org.orcid.core.orgs.fundref.localFilePath=/tmp/some/path

# ROR org imports
org.orcid.core.orgs.ror.enabled=false
org.orcid.core.orgs.ror.zenodoRecordsUrl=https://zenodo.org/api/records?communities=ror-data
org.orcid.core.orgs.ror.localDataPath=/tmp/ror/ror.json
org.orcid.core.orgs.ror.localZipPath=/tmp/ror/ror.zip

################
#      UI      #
################

# General
org.orcid.frontend.freemarker.cache=freemarker.cache.NullCacheStorage
org.orcid.frontend.static.resource.cache.enabled=false
org.orcid.frontend.web.domainsAllowingRobotsAsWhiteSpaceSeparatedList=orcid.org localhost localhost:8443/orcid-web

# Shibboleth
org.orcid.shibboleth.enabled=true

# Recaptcha
org.orcid.recaptcha.secret=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
org.orcid.recaptcha.verify_url=https://www.google.com/recaptcha/api/siteverify
org.orcid.recaptcha.web_site_key=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI

# spring-social
org.orcid.social.fb.key=xxx
org.orcid.social.fb.secret=xxxx
org.orcid.social.gg.key=xxxx
org.orcid.social.gg.secret=xxx

# Salesforce integration
org.orcid.microservice.gateway.url=https://localhost:8761
org.orcid.microservice.salesforce.token=X

# Account lockout
org.orcid.core.profile.lockout.threshhold=10
org.orcid.core.profile.lockout.window=5

# ISSN Loader Cron Configuration
org.orcid.scheduler.web.loadIssnCronConfig=0 0 0 * * FRI

# Added the config to index all RORs not only the changed ones
org.orcid.core.orgs.ror.indexAllEnabled=false

# Redis Cache
org.orcid.core.utils.cache.redis.host=reg-qa-redis-use2-m1.qa.int.orcid.org
org.orcid.core.utils.cache.redis.port=6379
org.orcid.core.utils.cache.redis.password=aVerySimpleToken
org.orcid.core.utils.cache.redis.enabled=true
org.orcid.core.utils.cache.redis.works-search-and-link-wizard.ttl=3600

#Autospam config
org.orcid.message-listener.s3.accessKey=xx
org.orcid.message-listener.s3.secretKey=xx
org.orcid.scheduler.aws.bucket=auto-spam-qa
org.orcid.scheduler.aws.file=orcidspam.csv
org.orcid.scheduler.autospam.enabled=false
org.orcid.scheduler.autospam.file=/Users/camdum/Desktop/orcidspam.csv
org.orcid.scheduler.autospam.daily.batch=20000
org.orcid.scheduler.autospam.process=0 0 0 * * MON

# Slack
org.orcid.core.autospam.slackChannel=collab-spam-reports
org.orcid.core.autospam.webhookUrl=

#org.orcid.persistence.liquibase.enabled=false
#org.orcid.persistence.solr.read.only.url=http://reg-qa-solr-use2-a1:8983/solr/
org.orcid.persistence.solr.read.only.url=http://localhost:8983/solr/
org.orcid.persistence.panoply.cleanup.production=false
#api_limiting_http_request_filter
org.orcid.persistence.panoply.papiExceededRate.production=false

# Panoply redshift database
org.orcid.core.utils.panoply.driver=com.amazon.redshift.jdbc.Driver
org.orcid.core.utils.panoply.maxPoolSize=20
org.orcid.core.utils.panoply.password=xxx
org.orcid.core.utils.panoply.idleConnectionTimeout=3600
org.orcid.core.utils.panoply.connectionTimeout=36000
#jdbc:redshift://<host>:<port>/<database>
org.orcid.core.utils.panoply.jdbcUrl=xxx
org.orcid.core.utils.panoply.username=xxx

#Slack channel for papi limits
org.orcid.core.papiLimitReport.slackChannel=system-alerts-qa
org.orcid.core.papiLimitReport.webhookUrl=xxx
org.orcid.papi.rate.limit.anonymous.requests=4
org.orcid.papi.rate.limit.known.requests=2
org.orcid.papi.rate.limit.enabled=true
org.orcid.scheduler.papiLimitReport.process=0 18 15 * * *

# Papi Limits Redis Cache
org.orcid.core.utils.cache.papi.redis.host=reg-qa-redisrate-use2-m1.qa.int.orcid.org
org.orcid.core.utils.cache.papi.redis.port=6379
org.orcid.core.utils.cache.papi.redis.password=xxxx
org.orcid.core.utils.cache.papi.redis.enabled=true

# CSRF Cookie settings
org.orcid.core.csrf.domain=dev.orcid.org
org.orcid.scheduler.web.processOrgsForIndexing=0 48 12 * * *
org.orcid.admin.registry.url=https://dev.orcid.org

org.orcid.core.passPhraseForInternalEncryption=XeZa8wUkuchusp8saWaW
org.orcid.core.passPhraseForExternalEncryption=spAbusa3ubRase7udEpr

# Redis to hold session data
org.orcid.core.session.cookie.domain=dev.orcid.org
org.orcid.core.utils.cache.session.redis.host=reg-qa-redissession-use2-m1.qa.int.orcid.org
org.orcid.core.utils.cache.session.redis.port=6379
org.orcid.core.utils.cache.session.redis.password=aVerySimpleToken
org.orcid.core.utils.cache.session.redis.pool.idle.max=50
org.orcid.core.utils.cache.session.redis.pool.max=300
org.orcid.core.utils.cache.session.redis.pool.wait.millis=1000
org.orcid.core.utils.cache.session.redis.connection_timeout_millis=2000
org.orcid.core.utils.cache.session.redis.session.timeout=600

org.orcid.utils.jwtKey=TtmMoTp!fxdb@9Au0i_OjfSNWHTXDIrz5S@REbqvXk#InZ&xul

org.orcid.core.cache.email_domain.timeToIdleSeconds=60