//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.17 at 04:05:45 PM GMT 
//


package xmlns.org.eurocris.cerif_api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import xmlns.org.eurocris.cerif_1.CERIF;


/**
 * <p>Java class for payloadtype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="payloadtype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{urn:xmlns:org:eurocris:cerif-1.6-2}CERIF"/>
 *         &lt;element ref="{urn:xmlns:org:eurocris:cerif-api}Entities"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "payloadtype", propOrder = {
    "cerif",
    "entities"
})
public class Payloadtype {

    @XmlElement(name = "CERIF", namespace = "urn:xmlns:org:eurocris:cerif-1.6-2")
    protected CERIF cerif;
    @XmlElement(name = "Entities")
    protected Entitylisttype entities;

    /**
     * Gets the value of the cerif property.
     * 
     * @return
     *     possible object is
     *     {@link CERIF }
     *     
     */
    public CERIF getCERIF() {
        return cerif;
    }

    /**
     * Sets the value of the cerif property.
     * 
     * @param value
     *     allowed object is
     *     {@link CERIF }
     *     
     */
    public void setCERIF(CERIF value) {
        this.cerif = value;
    }

    /**
     * Gets the value of the entities property.
     * 
     * @return
     *     possible object is
     *     {@link Entitylisttype }
     *     
     */
    public Entitylisttype getEntities() {
        return entities;
    }

    /**
     * Sets the value of the entities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Entitylisttype }
     *     
     */
    public void setEntities(Entitylisttype value) {
        this.entities = value;
    }

}
