//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.05 at 03:27:53 PM GMT 
//

package org.orcid.jaxb.model.v3.release.record;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlRootElement;

import io.swagger.annotations.ApiModel;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * 
 */
@XmlRootElement(name = "invited-position", namespace = "http://www.orcid.org/ns/invited-position")
@ApiModel(value = "InvitedPositionV3_0")
public class InvitedPosition extends Affiliation implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -8692419369122060879L;
}
