package org.orcid.jaxb.model.common;

import javax.xml.bind.annotation.XmlEnumValue;

public enum LanguageCode {
    @XmlEnumValue("ab") AB("ab"),
    @XmlEnumValue("aa") AA("aa"),
    @XmlEnumValue("af") AF("af"),
    @XmlEnumValue("ak") AK("ak"),
    @XmlEnumValue("sq") SQ("sq"),
    @XmlEnumValue("am") AM("am"),
    @XmlEnumValue("ar") AR("ar"),
    @XmlEnumValue("an") AN("an"),
    @XmlEnumValue("hy") HY("hy"),
    @XmlEnumValue("as") AS("as"),
    @XmlEnumValue("av") AV("av"),
    @XmlEnumValue("ae") AE("ae"),
    @XmlEnumValue("ay") AY("ay"),
    @XmlEnumValue("az") AZ("az"),
    @XmlEnumValue("bm") BM("bm"),
    @XmlEnumValue("ba") BA("ba"),
    @XmlEnumValue("eu") EU("eu"),
    @XmlEnumValue("be") BE("be"),
    @XmlEnumValue("bn") BN("bn"),
    @XmlEnumValue("bh") BH("bh"),
    @XmlEnumValue("bi") BI("bi"),
    @XmlEnumValue("bs") BS("bs"),
    @XmlEnumValue("br") BR("br"),
    @XmlEnumValue("bg") BG("bg"),
    @XmlEnumValue("my") MY("my"),
    @XmlEnumValue("ca") CA("ca"),
    @XmlEnumValue("ch") CH("ch"),
    @XmlEnumValue("ce") CE("ce"),
    @XmlEnumValue("zh_CN") ZH_CN("zh_CN"),
    @XmlEnumValue("zh_TW")ZH_TW ("zh_TW"),
    @XmlEnumValue("cu") CU("cu"),
    @XmlEnumValue("cv") CV("cv"),
    @XmlEnumValue("kw") KW("kw"),
    @XmlEnumValue("co") CO("co"),
    @XmlEnumValue("cr") CR("cr"),
    @XmlEnumValue("hr") HR("hr"),
    @XmlEnumValue("cs") CS("cs"),
    @XmlEnumValue("da") DA(""),
    @XmlEnumValue("dv") DV(""),
    @XmlEnumValue("nl") NL(""),
    @XmlEnumValue("dz") DZ(""),
    @XmlEnumValue("en") EN(""),
    @XmlEnumValue("eo") EO(""),
    @XmlEnumValue("et") ET(""),
    @XmlEnumValue("ee") EE(""),
    @XmlEnumValue("fo") FO(""),
    @XmlEnumValue("fj") FJ(""),
    @XmlEnumValue("fi") FI(""),
    @XmlEnumValue("fr") FR(""),
    @XmlEnumValue("fy") FY(""),
    @XmlEnumValue("ff") FF(""),
    @XmlEnumValue("gl") GL(""),
    @XmlEnumValue("lg") LG(""),
    @XmlEnumValue("ka") KA(""),
    @XmlEnumValue("de") DE(""),
    @XmlEnumValue("el") EL(""),
    @XmlEnumValue("kl") KL(""),
    @XmlEnumValue("gn") GN(""),
    @XmlEnumValue("gu") GU(""),
    @XmlEnumValue("ht") HT(""),
    @XmlEnumValue("ha") HA(""),
    @XmlEnumValue("iw") IW(""),
    @XmlEnumValue("hz") HZ(""),
    @XmlEnumValue("hi") HI(""),
    @XmlEnumValue("ho") HO(""),
    @XmlEnumValue("hu") HU(""),
    @XmlEnumValue("is") IS(""),
    @XmlEnumValue("io") IO(""),
    @XmlEnumValue("ig") IG(""),
    @XmlEnumValue("in") IN(""),
    @XmlEnumValue("ia") IA(""),
    @XmlEnumValue("ie") IE(""),
    @XmlEnumValue("iu") IU(""),
    @XmlEnumValue("ik") IK(""),
    @XmlEnumValue("ga") GA(""),
    @XmlEnumValue("it") IT(""),
    @XmlEnumValue("ja") JA(""),
    @XmlEnumValue("jv") JV(""),
    @XmlEnumValue("kn") KN(""),
    @XmlEnumValue("kr") KR(""),
    @XmlEnumValue("ks") KS(""),
    @XmlEnumValue("kk") KK(""),
    @XmlEnumValue("km") KM(""),
    @XmlEnumValue("ki") KI(""),
    @XmlEnumValue("rw") RW(""),
    @XmlEnumValue("ky") KY(""),
    @XmlEnumValue("kv") KV(""),
    @XmlEnumValue("kg") KG(""),
    @XmlEnumValue("ko") KO(""),
    @XmlEnumValue("ku") KU(""),
    @XmlEnumValue("kj") KJ(""),
    @XmlEnumValue("lo") LO(""),
    @XmlEnumValue("la") LA(""),
    @XmlEnumValue("lv") LV(""),
    @XmlEnumValue("li") LI(""),
    @XmlEnumValue("ln") LN(""),
    @XmlEnumValue("lt") LT(""),
    @XmlEnumValue("lu") LU(""),
    @XmlEnumValue("lb") LB(""),
    @XmlEnumValue("mk") MK(""),
    @XmlEnumValue("mg") MG(""),
    @XmlEnumValue("ms") MS(""),
    @XmlEnumValue("ml") ML(""),
    @XmlEnumValue("mt") MT(""),
    @XmlEnumValue("gv") GV(""),
    @XmlEnumValue("mi") MI(""),
    @XmlEnumValue("mr") MR(""),
    @XmlEnumValue("mh") MH(""),
    @XmlEnumValue("mo") MO(""),
    @XmlEnumValue("mn") MN(""),
    @XmlEnumValue("na") NA(""),
    @XmlEnumValue("nv") NV(""),
    @XmlEnumValue("ng") NG(""),
    @XmlEnumValue("ne") NE(""),
    @XmlEnumValue("nd") ND(""),
    @XmlEnumValue("se") SE(""),
    @XmlEnumValue("no") NO(""),
    @XmlEnumValue("nb") NB(""),
    @XmlEnumValue("nn") NN(""),
    @XmlEnumValue("ny") NY(""),
    @XmlEnumValue("oc") OC(""),
    @XmlEnumValue("oj") OJ(""),
    @XmlEnumValue("or") OR(""),
    @XmlEnumValue("om") OM(""),
    @XmlEnumValue("os") OS(""),
    @XmlEnumValue("pi") PI(""),
    @XmlEnumValue("pa") PA(""),
    @XmlEnumValue("fa") FA(""),
    @XmlEnumValue("pl") PL(""),
    @XmlEnumValue("pt") PT(""),
    @XmlEnumValue("ps") PS(""),
    @XmlEnumValue("qu") QU(""),
    @XmlEnumValue("rm") RM(""),
    @XmlEnumValue("ro") RO(""),
    @XmlEnumValue("rn") RN(""),
    @XmlEnumValue("ru") RU(""),
    @XmlEnumValue("sm") SM(""),
    @XmlEnumValue("sg") SG(""),
    @XmlEnumValue("sa") SA(""),
    @XmlEnumValue("sc") SC(""),
    @XmlEnumValue("gd") GD(""),
    @XmlEnumValue("sr") SR(""),
    @XmlEnumValue("sn") SN(""),
    @XmlEnumValue("ii") II(""),
    @XmlEnumValue("sd") SD(""),
    @XmlEnumValue("si") SI(""),
    @XmlEnumValue("sk") SK(""),
    @XmlEnumValue("sl") SL(""),
    @XmlEnumValue("so") SO(""),
    @XmlEnumValue("nr") NR(""),
    @XmlEnumValue("st") ST(""),
    @XmlEnumValue("es") ES(""),
    @XmlEnumValue("su") SU(""),
    @XmlEnumValue("sw") SW(""),
    @XmlEnumValue("ss") SS(""),
    @XmlEnumValue("sv") SV(""),
    @XmlEnumValue("tl") TL(""),
    @XmlEnumValue("ty") TY(""),
    @XmlEnumValue("tg") TG(""),
    @XmlEnumValue("ta") TA(""),
    @XmlEnumValue("tt") TT(""),
    @XmlEnumValue("te") TE(""),
    @XmlEnumValue("th") TH(""),
    @XmlEnumValue("bo") BO(""),
    @XmlEnumValue("ti") TI(""),
    @XmlEnumValue("to") TO(""),
    @XmlEnumValue("ts") TS(""),
    @XmlEnumValue("tn") TN(""),
    @XmlEnumValue("tr") TR(""),
    @XmlEnumValue("tk") TK(""),
    @XmlEnumValue("tw") TW(""),
    @XmlEnumValue("ug") UG(""),
    @XmlEnumValue("uk") UK(""),
    @XmlEnumValue("ur") UR(""),
    @XmlEnumValue("uz") UZ(""),
    @XmlEnumValue("ve") VE(""),
    @XmlEnumValue("vi") VI(""),
    @XmlEnumValue("vo") VO(""),
    @XmlEnumValue("wa") WA(""),
    @XmlEnumValue("cy") CY(""),
    @XmlEnumValue("wo") WO(""),
    @XmlEnumValue("xh") XH(""),
    @XmlEnumValue("ji") JI(""),
    @XmlEnumValue("yo") YO(""),
    @XmlEnumValue("za") ZA(""),
    @XmlEnumValue("zu") ZU("");
    
    String value;

    public LanguageCode(String value) {
        this.value = value;
    }
    
    public String getValue() {
        return value;
    }
    
    public LanguageCode fromValue(String value) {
        for(LanguageCode lc : LanguageCode.values()) {
            if(value.equals(lc.getValue())) {
                return lc;
            }
        }
        
        throw new IllegalArgumentException(value);
    }
}

