//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 11:29:18 AM GMT 
//


package xmlns.org.eurocris.cerif_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cfCurrencyEntName__Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cfCurrencyEntName__Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cfCurrCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cfEntName" type="{urn:xmlns:org:eurocris:cerif-1.6-2}cfMLangString__Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cfCurrencyEntName__Type", propOrder = {
    "cfCurrCode",
    "cfEntName"
})
public class CfCurrencyEntNameType {

    @XmlElement(required = true)
    protected String cfCurrCode;
    @XmlElement(required = true)
    protected CfMLangStringType cfEntName;

    /**
     * Gets the value of the cfCurrCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCfCurrCode() {
        return cfCurrCode;
    }

    /**
     * Sets the value of the cfCurrCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCfCurrCode(String value) {
        this.cfCurrCode = value;
    }

    /**
     * Gets the value of the cfEntName property.
     * 
     * @return
     *     possible object is
     *     {@link CfMLangStringType }
     *     
     */
    public CfMLangStringType getCfEntName() {
        return cfEntName;
    }

    /**
     * Sets the value of the cfEntName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CfMLangStringType }
     *     
     */
    public void setCfEntName(CfMLangStringType value) {
        this.cfEntName = value;
    }

}
