//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 11:29:18 AM GMT 
//


package xmlns.org.eurocris.cerif_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cfGender__Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="cfGender__Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="m"/>
 *     &lt;enumeration value="f"/>
 *     &lt;enumeration value="u"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cfGender__Type")
@XmlEnum
public enum CfGenderType {


    /**
     * Male
     * 
     */
    @XmlEnumValue("m")
    M("m"),

    /**
     * Female
     * 
     */
    @XmlEnumValue("f")
    F("f"),

    /**
     * Unknown
     * 
     */
    @XmlEnumValue("u")
    U("u");
    private final String value;

    CfGenderType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CfGenderType fromValue(String v) {
        for (CfGenderType c: CfGenderType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
