//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 11:29:18 AM GMT 
//


package xmlns.org.eurocris.cerif_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for cfPers_Lang__Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cfPers_Lang__Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cfPersId" type="{urn:xmlns:org:eurocris:cerif-1.6-2}cfId__Type"/>
 *         &lt;element name="cfLangCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;group ref="{urn:xmlns:org:eurocris:cerif-1.6-2}cfCoreClassWithFraction__Group"/>
 *         &lt;element name="cfSkillReading" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cfSkillSpeaking" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cfSkillWriting" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cfPers_Lang__Type", propOrder = {
    "cfPersId",
    "cfLangCode",
    "cfClassId",
    "cfClassSchemeId",
    "cfStartDate",
    "cfEndDate",
    "cfFraction",
    "cfSkillReading",
    "cfSkillSpeaking",
    "cfSkillWriting"
})
public class CfPersLangType {

    @XmlElement(required = true)
    protected String cfPersId;
    @XmlElement(required = true)
    protected String cfLangCode;
    @XmlElement(required = true)
    protected String cfClassId;
    @XmlElement(required = true)
    protected String cfClassSchemeId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cfStartDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cfEndDate;
    protected Float cfFraction;
    protected String cfSkillReading;
    protected String cfSkillSpeaking;
    protected String cfSkillWriting;

    /**
     * Gets the value of the cfPersId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCfPersId() {
        return cfPersId;
    }

    /**
     * Sets the value of the cfPersId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCfPersId(String value) {
        this.cfPersId = value;
    }

    /**
     * Gets the value of the cfLangCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCfLangCode() {
        return cfLangCode;
    }

    /**
     * Sets the value of the cfLangCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCfLangCode(String value) {
        this.cfLangCode = value;
    }

    /**
     * Gets the value of the cfClassId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCfClassId() {
        return cfClassId;
    }

    /**
     * Sets the value of the cfClassId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCfClassId(String value) {
        this.cfClassId = value;
    }

    /**
     * Gets the value of the cfClassSchemeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCfClassSchemeId() {
        return cfClassSchemeId;
    }

    /**
     * Sets the value of the cfClassSchemeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCfClassSchemeId(String value) {
        this.cfClassSchemeId = value;
    }

    /**
     * Gets the value of the cfStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCfStartDate() {
        return cfStartDate;
    }

    /**
     * Sets the value of the cfStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCfStartDate(XMLGregorianCalendar value) {
        this.cfStartDate = value;
    }

    /**
     * Gets the value of the cfEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCfEndDate() {
        return cfEndDate;
    }

    /**
     * Sets the value of the cfEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCfEndDate(XMLGregorianCalendar value) {
        this.cfEndDate = value;
    }

    /**
     * Gets the value of the cfFraction property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCfFraction() {
        return cfFraction;
    }

    /**
     * Sets the value of the cfFraction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCfFraction(Float value) {
        this.cfFraction = value;
    }

    /**
     * Gets the value of the cfSkillReading property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCfSkillReading() {
        return cfSkillReading;
    }

    /**
     * Sets the value of the cfSkillReading property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCfSkillReading(String value) {
        this.cfSkillReading = value;
    }

    /**
     * Gets the value of the cfSkillSpeaking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCfSkillSpeaking() {
        return cfSkillSpeaking;
    }

    /**
     * Sets the value of the cfSkillSpeaking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCfSkillSpeaking(String value) {
        this.cfSkillSpeaking = value;
    }

    /**
     * Gets the value of the cfSkillWriting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCfSkillWriting() {
        return cfSkillWriting;
    }

    /**
     * Sets the value of the cfSkillWriting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCfSkillWriting(String value) {
        this.cfSkillWriting = value;
    }

}
