//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.09 at 01:28:54 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.orcid.org/ns/error", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.orcid.jaxb.model.error_v2;
