/**
 * =============================================================================
 *
 * ORCID (R) Open Source
 * http://orcid.org
 *
 * Copyright (c) 2012-2013 ORCID, Inc.
 * Licensed under an MIT-Style License (MIT)
 * http://orcid.org/open-source-license
 *
 * This copyright and license information (including a link to the full license)
 * shall be included in its entirety in all copies or substantial portion of
 * the software.
 *
 * =============================================================================
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.12 at 12:31:47 PM BST 
//

package org.orcid.jaxb.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}disambiguated-affiliation-identifier"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}disambiguation-source"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "disambiguatedAffiliationIdentifier", "disambiguationSource" })
@XmlRootElement(name = "disambiguated-affiliation")
public class DisambiguatedAffiliation implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "disambiguated-affiliation-identifier", required = true)
    protected String disambiguatedAffiliationIdentifier;
    @XmlElement(name = "disambiguation-source", required = true)
    protected String disambiguationSource;

    /**
     * Gets the value of the disambiguatedAffiliationIdentifier property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDisambiguatedAffiliationIdentifier() {
        return disambiguatedAffiliationIdentifier;
    }

    /**
     * Sets the value of the disambiguatedAffiliationIdentifier property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDisambiguatedAffiliationIdentifier(String value) {
        this.disambiguatedAffiliationIdentifier = value;
    }

    /**
     * Gets the value of the disambiguationSource property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDisambiguationSource() {
        return disambiguationSource;
    }

    /**
     * Sets the value of the disambiguationSource property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDisambiguationSource(String value) {
        this.disambiguationSource = value;
    }

}
