//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.05 at 03:27:53 PM GMT 
//

package org.orcid.jaxb.model.v3.rc1.common;

import java.io.Serializable;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import org.orcid.jaxb.model.common_v2.DisambiguatedOrganizationExternalIdentifier;

/**
 * <p>
 * Java class for disambiguated-organization complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="disambiguated-organization">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}disambiguated-organization-identifier"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}disambiguation-source"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder = { "disambiguatedOrganizationIdentifier", "disambiguationSource" })
@XmlRootElement(name = "disambiguatedOrganization", namespace = "http://www.orcid.org/ns/common")
public class DisambiguatedOrganization implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true, namespace = "http://www.orcid.org/ns/common", name = "disambiguated-organization-identifier")
    protected String disambiguatedOrganizationIdentifier;
    @XmlElement(required = true, namespace = "http://www.orcid.org/ns/common", name = "disambiguation-source")
    protected String disambiguationSource;
    @XmlTransient
    protected Long id;
    @XmlTransient
    protected List<DisambiguatedOrganizationExternalIdentifier> externalIdentifiers;
    
    /**
     * Gets the value of the disambiguatedOrganizationIdentifier property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDisambiguatedOrganizationIdentifier() {
        return disambiguatedOrganizationIdentifier;
    }

    /**
     * Sets the value of the disambiguatedOrganizationIdentifier property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDisambiguatedOrganizationIdentifier(String value) {
        this.disambiguatedOrganizationIdentifier = value;
    }

    /**
     * Gets the value of the disambiguationSource property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDisambiguationSource() {
        return disambiguationSource;
    }

    /**
     * Sets the value of the disambiguationSource property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDisambiguationSource(String value) {
        this.disambiguationSource = value;
    }    
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public List<DisambiguatedOrganizationExternalIdentifier> getExternalIdentifiers() {
        return externalIdentifiers;
    }

    public void setExternalIdentifiers(List<DisambiguatedOrganizationExternalIdentifier> externalIdentifiers) {
        this.externalIdentifiers = externalIdentifiers;
    }
    
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((disambiguatedOrganizationIdentifier == null) ? 0 : disambiguatedOrganizationIdentifier.hashCode());
        result = prime * result + ((disambiguationSource == null) ? 0 : disambiguationSource.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DisambiguatedOrganization other = (DisambiguatedOrganization) obj;
        if (disambiguatedOrganizationIdentifier == null) {
            if (other.disambiguatedOrganizationIdentifier != null)
                return false;
        } else if (!disambiguatedOrganizationIdentifier.equals(other.disambiguatedOrganizationIdentifier))
            return false;
        if (disambiguationSource == null) {
            if (other.disambiguationSource != null)
                return false;
        } else if (!disambiguationSource.equals(other.disambiguationSource))
            return false;
        return true;
    }

}
