.github/workflows/azure-functions-app-java.ymlcorp-jones-damarcus:patch-1corp-jones-damarcus:mainhttps://github.com/corp-jones-damarcus/ORCID-Source.githttps://orcid.org/0000-0001-6666-1926name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
