name: lint

# we don't pay for pre-commit-ci yet so need this for private repos

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

on:
  workflow_call:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: pre-commit/action@576ff52938d158a24ac7e009dfa94b1455e7df99
