name: lint

# we don't pay for pre-commit-ci yet so need this for private repos

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

on:
  workflow_call:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: pre-commit/action@576ff52938d158a24ac7e009dfa94b1455e7df99
