name: lint

# we don't pay for pre-commit-ci yet so need this for private repos

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

on:
  workflow_call:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> "$GITHUB_ENV"
      - uses: actions/cache@v3
        with:
          path: ~/.cache
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      # lockdown all 3rd party repos to git shas
      #- uses: cloudposse/github-action-pre-commit@32acf3179b9eda817c0f549e8057477d320827db
      # migrate to standard pre-commit
      - uses: pre-commit/action@5f528da5c95691c4cf42ff76a4d10854b62cbb82
