name: SAST
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '45 6 * * 0'
jobs:
  buildmavenDepTree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Set up JDK 11
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Generate dependency tree
        run: |
          find . -name "pom.xml" -execdir mvn -q dependency:tree -DoutputFile=maven_dep_tree.txt -Dmaven.test.skip=true \;
      - name: Create zip with all dependency trees
        run: find . -type f -name 'maven_dep_tree.txt' -exec zip -r deptree.zip {} +
      - name: Upload zip
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: deptree
          path: deptree.zip
  sast:
    needs: buildmavenDepTree
    name: sast
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Download Maven Dependencies
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: deptree
      - name: Extract zip and run Semgrep
        run: |
          unzip -o deptree.zip
          semgrep ci --supply-chain > /dev/null 2>&1 || exit $?
          semgrep ci --code > /dev/null 2>&1 || exit $?          