name: test_mvn

permissions:
  checks: write
  contents: read
  actions: read

on:
  workflow_call:
    inputs:
      version_tag:
        description: 'Name of the tag to build'
        required: false
        default: 'latest'
        type: string
      bump:
        description: 'whether to bump the version number by a major minor patch amount or none'
        required: false
        default: 'patch'
        type: string
      ref:
        description: 'git reference to use with the checkout use default_branch to have that calculated'
        required: false
        default: "default"
        type: string
      seed_maven_cache:
        description: Whether to seed cache
        type: boolean
        required: false
        default: true
      install_maven_dependencies:
        description: Whether to install dependencies or use a previous cache
        type: boolean
        required: false
        default: true

  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Name of the tag to build'
        required: false
        default: 'latest'
        type: string
      bump:
        description: 'whether to bump the version number by a major minor patch amount or none'
        required: false
        default: 'patch'
        type: string
      ref:
        description: 'git reference to use with the checkout use default_branch to have that calculated'
        required: false
        default: "default"
        type: string
      seed_maven_cache:
        description: Whether to seed cache
        type: boolean
        required: false
        default: true
      install_maven_dependencies:
        description: Whether to install dependencies or use a previous cache
        type: boolean
        required: false
        default: true


jobs:
  test_mvn:
    strategy:
      matrix:
        include:
          - project: orcid-message-listener
          - project: orcid-activemq
          - project: orcid-api-web
          - project: orcid-internal-api
          - project: orcid-pub-web
          - project: orcid-scheduler-web
          - project: orcid-web
          - project: orcid-utils
          - project: orcid-core
          - project: orcid-persistence
          - project: orcid-api-common

    runs-on: ubuntu-latest
    steps:
      - name: git-checkout-ref-action
        id: ref
        uses: ORCID/git-checkout-ref-action@main
        with:
          default_branch: ${{ github.event.repository.default_branch }}
          ref: ${{ inputs.ref }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.ref.outputs.ref }}
          # checkout some history so we can scan commits for bump messages
          # NOTE: history does not include tags!
          fetch-depth: 100

      - name: find next version
        id: version
        uses: ORCID/version-bump-action@main
        with:
          version_tag: ${{ inputs.version_tag }}
          bump: ${{ inputs.bump }}

      - name: Set up Open JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

########################################################################################
# handle restoring a custom gha cache

      - name: if not installing dependencies restore special previous git_sha cache
        if:  ${{ ! inputs.install_maven_dependencies }}
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ steps.version.outputs.version_tag_numeric }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ steps.version.outputs.version_tag_numeric }}-${{ github.sha }}

      - name: bump version of the parent pom and connected projects
        if: ${{ ! inputs.install_maven_dependencies }}
        run: |
          mvn -T 1C --batch-mode versions:set -DskipTests \
              -DnewVersion="$version_tag_numeric" -DgenerateBackupPoms=false
        env:
          version_tag_numeric: "${{ steps.version.outputs.version_tag_numeric }}"

########################################################################################

      - name: if installing dependencies use a standard cache key name
        if: ${{ inputs.install_maven_dependencies }}
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-seed-cache
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-seed-cache

      - name: seed_maven_cache
        if: ${{ inputs.seed_maven_cache }}
        id: cache
        uses: ORCID/ORCID-Source-cache-action@main
        with:
          version_tag_numeric: ${{ steps.version.outputs.version_tag_numeric }}

      - name: install_dependencies and bump version
        if: ${{ inputs.install_maven_dependencies }}
        id: install_dependencies
        uses: ORCID/ORCID-Source-dependencies-action@main
        with:
          version_tag_numeric: ${{ steps.version.outputs.version_tag_numeric }}

########################################################################################
      - name: "Test ${{ matrix.project }}"
        run: |
          mvn -T 1C --batch-mode test \
              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
              --projects ${{ matrix.project }} --fail-at-end

      - name: Publish unit test report for non forked repo
        if: ${{ failure() && (github.event.pull_request.head.repo.full_name == github.repository) }} # only report if a test has failed and we are a non forked repo
        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1.9.1
        with:
          name: "Unit test report for ${{ matrix.project }}"
          path: ${{ matrix.project }}/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Annotate only test report for forked repo
        uses: mikepenz/action-junit-report@ec3a351c13e080dc4fa94c49ab7ad5bf778a9668 # v5
        if: ${{ failure() &&  (github.event.pull_request.head.repo.full_name != github.repository) }} # only report if a test has failed and we are a forked repo
        with:
          report_paths: ${{ matrix.project }}/target/surefire-reports/*.xml
          annotate_only: true # forked repo cannot write to checks so just do annotations
